Display github action unit test results

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -42,6 +42,15 @@ jobs:
 
       - name: Test NET6
         run: ./build.ps1 -target Test
+
+      - name: Windows unit test report
+        uses: dorny/test-reporter@v1
+        if: success() || failure()    # run this step even if previous step failed
+        with:
+          name: Windows unit test results
+          path: ./TestResults/*.trx
+          reporter: dotnet-trx
+          fail-on-error: true
         
   build-release-linux:
     needs: test-windows
@@ -59,6 +68,15 @@ jobs:
     - name: Nuke Build 🏗
       id: build
       run: ./build.sh --verbosity verbose
+
+    - name: Linux unit test report
+      uses: dorny/test-reporter@v1
+      if: success() || failure()    # run this step even if previous step failed
+      with:
+        name: Linux unit test results
+        path: ./TestResults/*.trx
+        reporter: dotnet-trx
+        fail-on-error: true
 
     - name: Tag release (when not pre-release) 🏷️
       if: ${{ github.event_name != 'schedule' && !contains( steps.build.outputs.octoversion_fullsemver, '-' ) }}
